version: '3.9'

services:
  headman_bot:
    env_file:
      - ./.env/.env
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /var/log/headman_bot:/app/logs
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env/.database.env
    volumes:
      - /var/lib/headman_bot_db:/var/lib/posgresql/data

  redis:
    image: redis:7.2.3
    restart: on-failure
