version: '3.9'

services:
  headman_bot:
    env_file:
      - ./.env/.env
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /var/log/headman_bot:/app/logs
      - /var/www/HeadmanBot/db_data:/app/db_data
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - ./.env/.database.env
    volumes:
      - postgres_headman_bot_data:/var/lib/posgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.3
    restart: on-failure
    ports:
      - 6380:6380
    volumes:
      - /var/www/HeadmanBot/db_data:/data

volumes:
  postgres_headman_bot_data:
  redis_data:
