version: '3.9'

services:
  headman_bot:
    env_file:
      - ./.env/.env
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /var/log/headman_bot:/app/logs
      - /var/www/HeadmanBot/db_data:/app/db_data
