version: '3.9'

services:
  headman_bot:
    env_file:
      - ./.env/.env
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /var/log/headman_bot:/app/logs
    depends_on:
      redis:
        condition: service_started
      postgres:
          condition: service_healthy

  postgres:
    command: postgres -c log_min_duration_statement=1000
    image: postgres
    restart: always
    env_file:
      - ./.env/.database.env
    volumes:
      - /var/lib/headman_bot_db:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    restart: on-failure
