version: '3.9'

services:
  headman_bot:
    env_file:
      - ./.env/.env
    build: 
      dockerfile: Dockerfile
    volumes:
      - /var/log/headman_bot:/app/logs
      - ./db_data/bot.db:/app/db_data
