version: '3.9'

services:
  postgres:
    command: postgres -c log_min_duration_statement=1000
    image: postgres
    env_file:
      - ./.env/.database.dev.env
    volumes:
      - headman_bot_postgres_dev_data:/var/lib/posgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  headman_bot:
    env_file:
      - ./.env/.dev.env
    build: 
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      postgres:
          condition: service_healthy
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7.2.3
    restart: on-failure

volumes:
  headman_bot_postgres_dev_data:
