version: '3.9'

services:
  headman_bot:
    env_file:
      - ../.env/.env
    build: 
      dockerfile: ./docker/Dockerfile
      context: ../
    volumes:
      - /var/log/headman_bot:/app/logs
      - PATH_TO_UPDATE_INFO_HTML_FILE_ON_SERVER:/app/logs
    depends_on:
      redis:
        condition: service_started
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/headman_bot_db:/var/lib/postgresql/data
      - ../postgresql.conf:/etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    restart: on-failure
