version: '3.9'

services:
  proxy:
    depends_on:
      - headman_bot
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - 443:443

  headman_bot:
    env_file:
      - ../.env/.env
    build: 
      dockerfile: ./docker/Dockerfile
      context: ../
    volumes:
      - /var/log/headman_bot:/app/logs
      - ../update_info.html:/app/update_info.html
      - ../poll_by_role.html:/app/poll_by_role.html
      - ../ShowInfoImg.png:/app/ShowInfoImg.png
    depends_on:
      redis:
        condition: service_started
      postgres:
          condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/headman_bot_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.3
    restart: on-failure
